name: Auto Approve and Merge Snyk-bot PRs

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:  # Allows manual triggering if needed

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub CLI Version
        run: gh --version

      - name: Approve Snyk PR
        # Ensure this step only runs on pull_request events and when the actor is snyk-bot
        if: github.event_name == 'pull_request' && github.actor == 'snyk-bot'
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Snyk PR
        # Ensure this step only runs on pull_request events and when the actor is snyk-bot
        if: github.event_name == 'pull_request' && github.actor == 'snyk-bot'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
