name: Auto Approve, Update, and Merge Snyk-bot PRs

on:
  pull_request:
    types: [opened, synchronize]  # Triggered only by pull_request events for new or updated PRs

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve-update-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Approve Snyk PR
        if: github.event_name == 'pull_request' && github.actor == 'snyk-bot'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Branch
        if: github.event_name == 'pull_request' && github.actor == 'snyk-bot'
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git fetch origin master
          git merge origin/master
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Snyk PR
        if: github.event_name == 'pull_request' && github.actor == 'snyk-bot'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
