name: Auto Approve and Merge Snyk-bot PRs

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'snyk-bot'  # Filters to run only on Snyk-bot PRs
    steps:
      - name: Approve Snyk PR
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Snyk PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
